services:
  youtube-streamer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-streamer
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - stream_downloads:/app/downloads

volumes:
  stream_downloads: