import { FFmpegStreamer } from "../../services/ffmpeg.js";
import { createYouTubeClient } from "./client.js";
import { fetchStreamFile } from "./fetch-stream-file.js";
import { GetRefreshtoken } from "./refreshtoken.js";
import { YouTubeLiveService } from "./youtube-setup.js";

const ACCOUNT_EMAIL =
  "hs947518@gmail.com";

let activeStreamer:
  | FFmpegStreamer
  | null = null;

let shuttingDown = false;

async function createLiveService():
  Promise<YouTubeLiveService> {
  const clientId =
    process.env.GOOGLE_CLIENT_ID;

  const clientSecret =
    process.env.GOOGLE_CLIENT_SECRET;

  if (!clientId?.trim()) {
    throw new Error(
      "GOOGLE_CLIENT_ID is not configured",
    );
  }

  if (!clientSecret?.trim()) {
    throw new Error(
      "GOOGLE_CLIENT_SECRET is not configured",
    );
  }

  const refreshToken =
    await GetRefreshtoken(
      ACCOUNT_EMAIL,
    );

  if (!refreshToken?.trim()) {
    throw new Error(
      `No YouTube refresh token found for ${ACCOUNT_EMAIL}`,
    );
  }

  const youtube =
    createYouTubeClient({
      clientId,
      clientSecret,
      refreshToken,
    });

  return new YouTubeLiveService(
    youtube,
  );
}

export async function LiveStream():
  Promise<void> {
  let streamer:
    | FFmpegStreamer
    | null = null;

  try {
    console.log(
      "[Stream] Starting long-running YouTube stream...",
    );

    // --------------------------------------------
    // 1. YouTube authentication
    // --------------------------------------------

    const liveService =
      await createLiveService();

    console.log(
      "[YouTube] Authentication successful",
    );

    // --------------------------------------------
    // 2. Create broadcast + stream + bind
    // --------------------------------------------

    const live =
      await liveService.createLive(
        {
          title:
            "Relaxing Piano Music",
          description:
            "Relaxing piano music - live",
          privacyStatus:
            "public",
        },
      );

    console.log(
      `[YouTube] Broadcast: ${live.broadcastId}`,
    );

    console.log(
      `[YouTube] Stream: ${live.streamId}`,
    );

    console.log(
      `[YouTube] Watch: ${live.watchUrl}`,
    );

    // --------------------------------------------
    // 3. Initial status
    // --------------------------------------------

    await liveService.logStreamStatus(
      live.streamId,
    );

    // --------------------------------------------
    // 4. Firebase video
    // --------------------------------------------

    const videoUrl =
      await fetchStreamFile(
        ACCOUNT_EMAIL,
      );

    if (!videoUrl?.trim()) {
      throw new Error(
        "Firebase video URL was not returned",
      );
    }

    console.log(
      `[Storage] Video source ready: ${videoUrl}`,
    );

    // --------------------------------------------
    // 5. FFmpeg
    // --------------------------------------------

    streamer =
      new FFmpegStreamer({
        videoUrl,

        /*
         * IMPORTANT:
         * This is generated by YouTube from
         * ingestionAddress + streamName.
         */
        rtmpUrl:
          live.rtmpUrl,

        width: 1920,
        height: 1080,
        fps: 30,

        /*
         * Existing source is H.264/AAC,
         * so avoid transcoding.
         */
        copyVideo: true,
        copyAudio: true,

        loop: true,

        startupTimeoutMs:
          30_000,
      });

    activeStreamer =
      streamer;

    // --------------------------------------------
    // 6. FFmpeg events
    // --------------------------------------------

    streamer.on(
      "spawn",
      ({ pid }) => {
        console.log(
          `[FFmpeg] Process started, PID=${pid}`,
        );
      },
    );

    streamer.on(
      "started",
      () => {
        console.log(
          "[FFmpeg] Output initialized",
        );
      },
    );

    streamer.on(
      "log",
      (message: string) => {
        console.log(
          `[FFmpeg] ${message}`,
        );
      },
    );

    streamer.on(
      "stdout",
      (message: string) => {
        const output =
          message.trim();

        if (output) {
          console.log(
            `[FFmpeg stdout] ${output}`,
          );
        }
      },
    );

    streamer.on(
      "ffmpegWarning",
      (message: string) => {
        console.warn(
          `[FFmpeg warning] ${message}`,
        );
      },
    );

    streamer.on(
      "error",
      (error: Error) => {
        console.error(
          `[FFmpeg error] ${error.message}`,
        );
      },
    );

    streamer.on(
      "closed",
      (result) => {
        console.log(
          "[FFmpeg closed]",
          result,
        );
      },
    );

    // --------------------------------------------
    // 7. Start FFmpeg
    // --------------------------------------------

    console.log(
      "[FFmpeg] Starting 1080p30 stream...",
    );

    await streamer.start();

    console.log(
      "[FFmpeg] Encoder/output started",
    );

    // --------------------------------------------
    // 8. Wait for YouTube ingestion
    // --------------------------------------------

    console.log(
      "[YouTube] Waiting for ingestion...",
    );

    await liveService.waitForStreamActive(
      live.streamId,
      {
        timeoutMs:
          60_000,
        intervalMs:
          3_000,
      },
    );

    console.log(
      "[YouTube] Ingestion is ACTIVE",
    );

    // --------------------------------------------
    // 9. Wait for broadcast to become LIVE
    // --------------------------------------------

    console.log(
      "[YouTube] Waiting for broadcast to become LIVE...",
    );

    await liveService.waitForBroadcastLive(
      live.broadcastId,
      {
        timeoutMs:
          60_000,
        intervalMs:
          3_000,
      },
    );

    console.log(
      "[YouTube] Broadcast is LIVE",
    );

    console.log(
      `[YouTube] Watch URL: ${live.watchUrl}`,
    );

    console.log(
      "[Stream] Long-running stream is active",
    );

    // --------------------------------------------
    // 10. Keep Node alive until FFmpeg exits
    // --------------------------------------------

    await waitForProcessToClose(
      streamer,
    );

    /*
     * If FFmpeg exits without SIGINT/SIGTERM,
     * consider it an unexpected failure.
     */
    if (!shuttingDown) {
      throw new Error(
        "FFmpeg stopped unexpectedly",
      );
    }
  } catch (error) {
    console.error(
      "[LiveStream] Failed:",
      error instanceof Error
        ? error.message
        : String(error),
    );

    // --------------------------------------------
    // Cleanup
    // --------------------------------------------

    if (
      streamer?.running
    ) {
      try {
        console.log(
          "[FFmpeg] Stopping after failure...",
        );

        await streamer.stop();
      } catch (stopError) {
        console.error(
          "[FFmpeg] Cleanup failed:",
          stopError,
        );
      }
    }

    throw error;
  } finally {
    if (
      activeStreamer ===
      streamer
    ) {
      activeStreamer =
        null;
    }
  }
}

/**
 * Wait until FFmpeg exits.
 */
function waitForProcessToClose(
  streamer: FFmpegStreamer,
): Promise<void> {
  if (!streamer.running) {
    return Promise.resolve();
  }

  return new Promise<void>(
    (resolve) => {
      streamer.once(
        "closed",
        () => resolve(),
      );
    },
  );
}

/**
 * Gracefully stop FFmpeg when Docker
 * or the operating system sends a signal.
 */
async function shutdown(
  signal: NodeJS.Signals,
): Promise<void> {
  if (shuttingDown) {
    return;
  }

  shuttingDown = true;

  console.log(
    `[Process] Received ${signal}`,
  );

  const streamer =
    activeStreamer;

  if (!streamer) {
    console.log(
      "[Process] No active FFmpeg process",
    );

    process.exit(0);
    return;
  }

  try {
    console.log(
      "[FFmpeg] Stopping stream gracefully...",
    );

    await streamer.stop();

    console.log(
      "[FFmpeg] Stream stopped",
    );

    process.exit(0);
  } catch (error) {
    console.error(
      "[Process] Failed to stop FFmpeg:",
      error,
    );

    process.exit(1);
  }
}

// --------------------------------------------
// Docker / OS signals
// --------------------------------------------

process.once(
  "SIGINT",
  () => {
    void shutdown("SIGINT");
  },
);

process.once(
  "SIGTERM",
  () => {
    void shutdown("SIGTERM");
  },
);

// --------------------------------------------
// Entry point
// --------------------------------------------

try {
  await LiveStream();
} catch (error) {
  console.error(
    "[LiveStream] Fatal error:",
    error instanceof Error
      ? error
      : String(error),
  );

  process.exitCode = 1;
}